name: CI

on:
    push:
        branches: [ main, develop ]
    pull_request:
        branches: [ main, develop ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: [ 7.4, 8.1, 8.2, 8.3 ]
                magento-version: [ 2.4.6, 2.4.7 ]

        name: PHP ${{ matrix.php-version }} - Magento ${{ matrix.magento-version }}

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: bcmath, ctype, curl, dom, gd, hash, iconv, intl, mbstring, openssl, pdo_mysql, simplexml, soap, xsl, zip
                    tools: composer:v2, cs2pr

            -   name: Validate composer.json
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php-version }}-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run PHP CodeSniffer
                run: |
                    if [ -f "vendor/bin/phpcs" ]; then
                      vendor/bin/phpcs --standard=Magento2 --ignore=vendor/,.*/ --extensions=php,phtml . --report=checkstyle | cs2pr
                    else
                      composer require --dev magento/magento-coding-standard
                      vendor/bin/phpcs --standard=Magento2 --ignore=vendor/,.*/ --extensions=php,phtml . --report=checkstyle | cs2pr
                    fi

            -   name: Run PHPStan
                run: |
                    if [ -f "vendor/bin/phpstan" ]; then
                      vendor/bin/phpstan analyse --error-format=github
                    else
                      composer require --dev phpstan/phpstan
                      vendor/bin/phpstan analyse --error-format=github
                    fi

            -   name: Run PHP Mess Detector
                run: |
                    if [ -f "vendor/bin/phpmd" ]; then
                      vendor/bin/phpmd . github cleancode,codesize,controversial,design,naming,unusedcode --exclude vendor/,.*/ --suffixes php,phtml
                    else
                      composer require --dev phpmd/phpmd
                      vendor/bin/phpmd . github cleancode,codesize,controversial,design,naming,unusedcode --exclude vendor/,.*/ --suffixes php,phtml
                    fi

    security:
        runs-on: ubuntu-latest
        name: Security Check

        steps:
            -   uses: actions/checkout@v3

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    tools: composer:v2

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run security check
                run: |
                    if [ -f "vendor/bin/security-checker" ]; then
                      vendor/bin/security-checker security:check composer.lock
                    else
                      composer require --dev enlightn/security-checker
                      vendor/bin/security-checker security:check composer.lock
                    fi

    release:
        needs: [ test, security ]
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        name: Create Release

        steps:
            -   uses: actions/checkout@v3

            -   name: Create Release
                uses: actions/create-release@v1
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ github.ref }}
                    release_name: Release ${{ github.ref }}
                    body: |
                        Changes in this Release
                        - See CHANGELOG.md for details
                    draft: false
                    prerelease: false
